### PR TITLE
Voila tutorial notebook: organics notebook

### PR DESCRIPTION
**Pull request by lfunderburk**
Supporting material for https://github.com/ploomber/ploomber.io/pull/82

### CODE REVIEW

**Comment by lfunderburk** [comment]
Hi Eduardo, Ido and Tony,

Was experimenting with the yaml, config and requirements/runtime files to test Binder deployment as a standalone app, but it didn't build the way I expected. Open to feedback/changes. 
For now it is just the notebook component with Voila and interactive SQL

**Comment by lfunderburk** [comment]
I also wanted to share a bit of what went through my process
Yesterday the problem I was optimizing for was the dashboard experience, namely, the user changes a parameter and both the query and visualization updates accordingly.

I could also experiment with the ggplot flag to try to run the same workflow only with the %%sql magic.

Let me know your thoughts

**Comment by lfunderburk** [comment]
Something like that :) 
I will continue prototyping the dashboard to play with different layouts. 
The way I set up the query is a bit different from JupySQL's documentation, but it is still connecting and performing it successfully. 
The functions will make it easier to then move components around like I need.

**Comment by edublancas** [comment]
Great work! I tested it and works! Some feedback.

The setup instructions are in the post itself right? In case we don't have them, these are the steps I took to run it:

```sh
conda create --name voila-tutorial python=3.10 -y
pip install -r requirements.txt
voila organics-dashboard.ipynb
```

What are `app.yaml`  and `runtime.txt`? they look like google cloud deployment configuration files. Maybe the second part of the blog post can be how to deploy this dashboard into Heroku/Google cloud? For this first part, I think we can leave the deployment part out and only show how to run locally.

I noticed that the first cell in the notebook has some `pip install` command. This slows down the dashboard initialization, it's better to have this as a setup step and then remove the cell from the notebook. I tested it, and speeds up initialization.

What happens if you use our `--interact` built-in feature? It doesn't work? I'm ok with your existing solution; we can go with it, but if you can share some feedback so we improve the feature that would be great!

**Comment by lfunderburk** [comment]
Thank you Eduardo. 

Noted. Will make changes on the set up front to incorporate your suggestion and focus this part on local deployment. 

> What happens if you use our --interact built-in feature? It doesn't work? I'm ok with your existing solution; we can go with it, but if you can share some feedback so we improve the feature that would be great! 

I used the --interact flag and was able to update the queries, but had difficulty with updating the figure. Tony pointed me to an existing issue tackling this. https://github.com/ploomber/jupysql/issues/304 

I shared that before merging I can also replace the plotting functionality to use ggplot API instead. 

Would this be ok? would you rather we move with pushing it as is (plus the changes requested)?

**Comment by edublancas** [comment]
ok, let's move forward with the current implementation (no need to wait for `--interact` fixes)

please request my review once you address the changes.

**Comment by lfunderburk** [comment]
@edublancas  incorporated feedback, ready for review

**Review by edublancas — CHANGES_REQUESTED** [review]
one small thing I forgot: what's the source for organics.csv? It's better not to include this file in our repository since redistribution might not be allowed. if that's the case, add a link to the original source in the blog so people can download it

**Comment by lfunderburk** [comment]
License is unknown 

https://www.kaggle.com/datasets/papercool/organics-purchase-indicator?utm_source=ploomber&utm_medium=blog&utm_campaign=voila-tutorial

You're right, it's better that I link it and add a note to what prep steps are needed to make the scripts work.

**Comment by edublancas** [comment]
what was the final solution? 

perhaps we can tell users to download the dataset and then have a script to preprocess it and generate organics.csv?

 let me know!

also, for future blog posts: let's avoid kaggle datasets since they readers require an account to download them

**Comment by lfunderburk** [comment]
Final solution 

User would have needed to create account, and generate API key. I see why this is not ideal. The user now needs to move away from the blog to create an account, there are barriers,.

```
import kaggle
import pandas as pd
kaggle.api.authenticate()
kaggle.api.dataset_download_files('papercool/organics-purchase-indicator', path='./', unzip=True)

# Perform data cleaning
df = pd.read_csv('organics.csv')
df = df.dropna()

# Rename columns: substitute spaces with underscores
df.columns = [c.replace(' ', '_') for c in df.columns]

# Convert Affluence_Grade, Age, Frequency_Percent to numeric
df['Affluence_Grade'] = pd.to_numeric(df['Affluence_Grade'], errors='coerce')
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Frequency_Percent'] = pd.to_numeric(df['Frequency_Percent'], errors='coerce')

# Save the cleaned dataframe to local CSV file
df.to_csv('organics_cleaned.csv', index=False)
```

**Comment by lfunderburk** [comment]
The rest of the queries then interact with the data using organics_cleaned.csv

```
%%sql
SELECT Geographic_Region, Loyalty_Status, Television_Region FROM organics_cleaned.csv LIMIT 5
```

**Pull request merged**
